- hosts: master
  become: yes
  tasks:
    - name: initialize master
      shell: kubeadm init --pod-network-cidr=172.17.0.0/16 --apiserver-advertise-address=172.31.19.134
    - name: create kube dir
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: initialized pod network
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> initialized_pod_network.txt
      args:
        chdir: $HOME
        creates: initialized_pod_network.txt

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- hosts: worker
  become: yes
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
